### ISSUE TITLE
[bug] issue fetching from reviews with large length

### ISSUE THREAD

**Issue by abhishekyelley** [linuxdotexe/boxdp#4]
Edit: It's not just large reviews, i have another example where it fails
Link to test:
- https://letterboxd.com/abhishekyelley/film/jigarthanda-doublex/

While I was still writing this edit, it worked again somehow:
![Error and then worked](https://github.com/linuxdotexe/boxdp/assets/94790503/a9fdb988-a472-4372-aa61-29738f932c24 "HOW!?")
First few times it didn't work. Then i pressed the view review and submit buttons in some order (I can't remember) and then it after the submit, it worked

***

### 1. Lengthy review is the first item requested
![First Error: First item requested](https://github.com/linuxdotexe/boxdp/assets/94790503/0bfd1783-d2a0-4bda-a587-7ccd3e5f8db6 "First Error")
 
### 2. Lengthy review is requested after a non-lengthy review
![Second Error: Lengthy review is  requested after something else](https://github.com/linuxdotexe/boxdp/assets/94790503/1deca23a-e7b8-4d42-bf29-46bb77ae2ac1 "Second Error")

* NOTE: requesting a lengthy review after another lengthy review shows the same error as "First Error"

### Review links for testing:
Lengthy reviews  for testing:
- https://letterboxd.com/adpadgaonkar/film/jaya-jaya-jaya-jaya-hey/
- https://letterboxd.com/jameskl/film/salaar-part-1-ceasefire/

Good reviews for testing:
- https://letterboxd.com/andy09_/film/chicken-run-dawn-of-the-nugget/

**Comment by abhishekyelley** [comment]
THE LINK I PROVIDED AT THE TOP WORKS NOW WHYY!!??

**Comment by abhishekyelley** [comment]
The trick seems to be:
* submit
* press view review twice
* submit
And it works

**Comment by linuxdotexe** [comment]
> The trick seems to be:
> 
> * submit
> * press view review twice
> * submit
>   And it works

~~i will rewrite that view review button. this is weird, unwanted, disrespectful behavior.~~

I think that's probably how the Link tag works. When you click the View Submit button for the first time, it navigates you to that element. When you go up and click the same button the second time or refresh the page with the tag in the URL, it think's its already there and doesn't do anything?

It's also happening when you click immediately, so that's there too.
